# Pull in the C1-owned PL device-tree fragment alongside system-user.dtsi.
# system-user.dtsi is auto-fetched by Petalinux from the same files/ dir;
# spike-accel.dtsi and uio_config.dts are custom and must be declared
# explicitly so they land in ${WORKDIR}/ where the /include/ lines in
# system-user.dtsi can resolve them.
#
# uio_config.dts is auto-generated by tools/ci/gen_dts.py from
# hw/vivado/out/address_map.yaml; it's staged into files/ by
# sw/petalinux/scripts/fetch_app_sources.sh (Cloud Claude URGENT_ASK_9
# 376e2c5, 2026-05-28).

SRC_URI:append = " file://spike-accel.dtsi file://uio_config.dts"
FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
