# hw/vivado/build_bitstream.tcl — synth + impl + write_bitstream + reports.
#
# Pre-req: build_bd.tcl has been run and out/spike_zybo.xpr exists.

set PROJECT spike_zybo
set OUT_DIR [file normalize "[file dirname [info script]]/out"]
set REPORTS [file normalize "[file dirname [info script]]/reports"]
file mkdir $REPORTS

open_project [file join $OUT_DIR ${PROJECT}.xpr]

# ===== Workaround for URGENT_ASK_11 ============================================
# Some Vivado 2024.1 installs ship a partial roe_framer IP whose
# `data/rsb/rules/roe_framer/bd.tcl` startup rule sources a missing
# `data/ip/xilinx/roe_framer_v3_0/automation/auto_utils.tcl`. The rule's
# outer guard is `if {[llength [get_ipdefs *roe_framer*]] > 0}`, so disabling
# the partial roe_framer IP defs in the catalog before any launch_runs call
# prevents the failing source.
#
# v2 (per Remote feedback in run_step6_bt_patched.tcl): valid options for
# update_ip_catalog in 2024.1 are -disable_ip / -delete_ip / -enable_ip and
# they REQUIRE -repo_path. The earlier -delete_ipdef flag was rejected.
# We default repo_path to $XILINX_VIVADO/data/ip (set by Vivado settings64),
# which holds the broken roe_framer install.
if {[info exists ::env(XILINX_VIVADO)]} {
    set _xlnx_ip [file join $::env(XILINX_VIVADO) data ip]
} else {
    set _xlnx_ip ""
}
# Install-quirk disable list (kept in sync with build_bd.tcl). Some Vivado
# 2024.1 installs ship partial IP packages whose bd_rule helper TCLs
# reference missing files; this list disables them in catalog before
# launch_runs so the IPCACHE walk doesn't trip on them.
#
# v4 (URGENT_ASK_21): switched from NAME wildcards to exact VLNV strings.
# Wildcard *microblaze* matched 6+ entries (microblaze, microblaze_riscv,
# mdm_microblaze_riscv, microblaze_mcs, ...) and disabling them all
# corrupted BD rule init. Each exact VLNV is one entry.
set _broken_ip_vlnvs {
    xilinx.com:ip:roe_framer:3.0
    xilinx.com:ip:hdmi_gt_controller:1.0
    xilinx.com:ip:l_ethernet:3.2
    xilinx.com:ip:microblaze:11.0
}
foreach _vlnv $_broken_ip_vlnvs {
    if {$_xlnx_ip ne ""} {
        if {[catch {update_ip_catalog -disable_ip $_vlnv -repo_path $_xlnx_ip} _err]} {
            puts "INFO: $_vlnv not in catalog / already disabled — skipping ($_err)"
        } else {
            puts "INFO: Disabled broken IP $_vlnv"
        }
    }
}
unset -nocomplain _broken_ip_vlnvs _vlnv _xlnx_ip _err
# ==============================================================================

# IPCACHE multi-thread check appears to crash silently in some 2024.1 installs.
# Disable IP cache + serialize tool threading (M2-W2 sync from Remote: even
# launch_runs -jobs 1 isn't enough on a fresh BD — the IPCACHE runCacheChecks()
# threadPool finishes Work() can still crash; general.maxThreads 1 fully fixes it).
catch { set_param ip.useCacheStrategy 0 }
catch { set_param ip.checkLicense 0 }
catch { set_param ip.useIpCache 0 }
catch { set_param project.disableIPCache 1 }
catch { set_param general.maxThreads 1 }

# ===== Synth =====
launch_runs synth_1 -jobs 1
wait_on_run synth_1

# ===== Impl =====
launch_runs impl_1 -to_step write_bitstream -jobs 1
wait_on_run impl_1

# ===== Reports =====
open_run impl_1
report_timing_summary -file [file join $REPORTS timing_summary.rpt]
report_utilization     -file [file join $REPORTS utilization.rpt]
report_power           -file [file join $REPORTS power.rpt]

# ===== Export bitstream + hardware platform =====
set IMPL_DIR [file join $OUT_DIR ${PROJECT}.runs impl_1]
catch {file copy -force [file join $IMPL_DIR system_wrapper.bit] [file join $OUT_DIR system.bit]}
catch {file copy -force [file join $IMPL_DIR system_wrapper.ltx] [file join $OUT_DIR system.ltx]}
write_hw_platform -fixed -force -file [file join $OUT_DIR system.xsa]

# ===== Emit address_map.yaml (Contract 4) =====
set yaml_path [file join $OUT_DIR address_map.yaml]
set fp [open $yaml_path w]
puts $fp "# Auto-generated by build_bitstream.tcl after Vivado implementation."
puts $fp "soc: zynq-7020"
puts $fp "board: zybo-z7-20"
puts $fp "vivado_version: \"2024.1\""
puts $fp "bitstream: out/system.bit"
puts $fp "hwh: out/system.hwh"
puts $fp "peripherals:"
foreach seg [get_bd_addr_segs -of [get_bd_addr_spaces /ps_0/Data]] {
    set name [get_property NAME $seg]
    set base [get_property OFFSET $seg]
    set size [get_property RANGE $seg]
    puts $fp "  ${name}:"
    puts $fp "    base: ${base}"
    puts $fp "    size: ${size}"
}
puts $fp "memory:"
puts $fp "  ddr3:"
puts $fp "    total_mb: 1024"
puts $fp "    reserved_for_cma: 256"
close $fp

puts "============================================================"
puts "OK — bitstream + reports in ${REPORTS}/"
puts "     address_map.yaml -> ${yaml_path}"
puts "============================================================"
