# hw/vivado/build_bitstream.tcl — synth + impl + write_bitstream + reports.
#
# Pre-req: build_bd.tcl has been run and out/spike_zybo.xpr exists.

set PROJECT spike_zybo
set OUT_DIR [file normalize "[file dirname [info script]]/out"]
set REPORTS [file normalize "[file dirname [info script]]/reports"]
file mkdir $REPORTS

open_project [file join $OUT_DIR ${PROJECT}.xpr]

# ===== Workaround for URGENT_ASK_11 ============================================
# Some Vivado 2024.1 installs ship a partial roe_framer IP whose
# `data/rsb/rules/roe_framer/bd.tcl` startup rule sources a missing
# `data/ip/xilinx/roe_framer_v3_0/automation/auto_utils.tcl`. The rule's
# outer guard is `if {[llength [get_ipdefs *roe_framer*]] > 0}`, so removing
# the partial roe_framer IP defs from the catalog before any launch_runs
# call prevents the failing source. Only takes effect if the partial install
# is detected; clean installs short-circuit harmlessly.
set _roe_defs [get_ipdefs -quiet -filter {NAME =~ *roe_framer*}]
if {[llength $_roe_defs] > 0} {
    puts "INFO: Detected partial roe_framer IP in catalog — removing to avoid"
    puts "      auto_utils.tcl-missing error at launch_runs startup."
    foreach _idef $_roe_defs {
        if {[catch {update_ip_catalog -delete_ipdef $_idef} _err]} {
            puts "WARN: could not delete $_idef: $_err"
        }
    }
}
unset -nocomplain _roe_defs _idef _err
# ==============================================================================

# ===== Synth =====
launch_runs synth_1 -jobs 8
wait_on_run synth_1

# ===== Impl =====
launch_runs impl_1 -to_step write_bitstream -jobs 8
wait_on_run impl_1

# ===== Reports =====
open_run impl_1
report_timing_summary -file [file join $REPORTS timing_summary.rpt]
report_utilization     -file [file join $REPORTS utilization.rpt]
report_power           -file [file join $REPORTS power.rpt]

# ===== Export bitstream + hardware platform =====
set IMPL_DIR [file join $OUT_DIR ${PROJECT}.runs impl_1]
catch {file copy -force [file join $IMPL_DIR system_wrapper.bit] [file join $OUT_DIR system.bit]}
catch {file copy -force [file join $IMPL_DIR system_wrapper.ltx] [file join $OUT_DIR system.ltx]}
write_hw_platform -fixed -force -file [file join $OUT_DIR system.xsa]

# ===== Emit address_map.yaml (Contract 4) =====
set yaml_path [file join $OUT_DIR address_map.yaml]
set fp [open $yaml_path w]
puts $fp "# Auto-generated by build_bitstream.tcl after Vivado implementation."
puts $fp "soc: zynq-7020"
puts $fp "board: zybo-z7-20"
puts $fp "vivado_version: \"2024.1\""
puts $fp "bitstream: out/system.bit"
puts $fp "hwh: out/system.hwh"
puts $fp "peripherals:"
foreach seg [get_bd_addr_segs -of [get_bd_addr_spaces /ps_0/Data]] {
    set name [get_property NAME $seg]
    set base [get_property OFFSET $seg]
    set size [get_property RANGE $seg]
    puts $fp "  ${name}:"
    puts $fp "    base: ${base}"
    puts $fp "    size: ${size}"
}
puts $fp "memory:"
puts $fp "  ddr3:"
puts $fp "    total_mb: 1024"
puts $fp "    reserved_for_cma: 256"
close $fp

puts "============================================================"
puts "OK — bitstream + reports in ${REPORTS}/"
puts "     address_map.yaml -> ${yaml_path}"
puts "============================================================"
