"""Contract 4: address_map.yaml -> uio_config.dts (deterministic).

CI invariant: re-running this script must produce a byte-identical .dts.
``tests/test_address_map.py`` enforces it.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Dict, List

import yaml


# PL IRQ numbers map to SPI #N where N = irq_number - 32. Zynq-7000 PL IRQs
# are routed to GIC SPI 61..95 by the PS irqf2p block.
PL_IRQ_OFFSET = 32

# Header pinned so byte-for-byte diffs against committed file work even when
# tooling versions drift.
_HEADER = """\
/*
 * Auto-generated by tools/ci/gen_dts.py from address_map.yaml.
 * DO NOT EDIT BY HAND. Regenerate after every Vivado BD change.
 * Contract 4 in docs/CONTRACTS.md.
 */
"""


def _load(path: Path) -> Dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _validate(spec: Dict) -> List[str]:
    """Return a list of error strings (empty == OK)."""
    errs: List[str] = []
    peri = spec.get("peripherals", {})
    if not peri:
        errs.append("no peripherals declared")
        return errs

    # 1. Required keys
    for name, p in peri.items():
        for k in ("base", "size"):
            if k not in p:
                errs.append(f"{name}: missing '{k}'")
        if "irq" in p and not isinstance(p["irq"], int):
            errs.append(f"{name}: irq must be int")
        if "irq" in p:
            if not (61 <= p["irq"] <= 95):
                errs.append(f"{name}: irq {p['irq']} outside PL range [61, 95]")

    # 2. No address overlap
    ranges: List = []
    for name, p in peri.items():
        if "base" in p and "size" in p:
            base = int(p["base"])
            end  = base + int(p["size"]) - 1
            ranges.append((base, end, name))
    ranges.sort()
    for i in range(1, len(ranges)):
        prev_b, prev_e, prev_n = ranges[i - 1]
        b, e, n = ranges[i]
        if b <= prev_e:
            errs.append(
                f"address overlap: {prev_n} [{prev_b:#x}..{prev_e:#x}] vs "
                f"{n} [{b:#x}..{e:#x}]"
            )

    # 3. No IRQ collision
    seen_irq: Dict[int, str] = {}
    for name, p in peri.items():
        if "irq" in p:
            irq = p["irq"]
            if irq in seen_irq:
                errs.append(f"irq {irq} used by both {seen_irq[irq]} and {name}")
            seen_irq[irq] = name
    return errs


def render(spec: Dict) -> str:
    """Render address_map dict -> .dts text (deterministic).

    Peripherals are emitted in ascending base address order so the output
    is independent of YAML dict ordering.
    """
    out: List[str] = [_HEADER, "&amba_pl {", '\tcompatible = "simple-bus";'
                                              ' #address-cells = <1>;'
                                              ' #size-cells = <1>;', ""]
    peri = spec.get("peripherals", {})
    sorted_items = sorted(peri.items(), key=lambda kv: int(kv[1]["base"]))

    for name, p in sorted_items:
        base = int(p["base"])
        size = int(p["size"])
        node_name = f"{name}@{base:08x}"
        out.append(f"\t{name}: {node_name} {{")
        compat = p.get("compatible") or p.get("compat") or "generic-uio"
        out.append(f'\t\tcompatible = "{compat}";')
        out.append(f"\t\treg = <{base:#x} {size:#x}>;")
        if "irq" in p:
            spi = p["irq"] - PL_IRQ_OFFSET
            out.append(f"\t\tinterrupts = <0 {spi} 4>;")
            out.append("\t\tinterrupt-parent = <&intc>;")
        if p.get("clocks"):
            clk_list = ", ".join(f'"{c}"' for c in p["clocks"])
            out.append(f"\t\tclock-names = {clk_list};")
        out.append("\t};")
        out.append("")

    out.append("};")
    out.append("")    # trailing newline
    return "\n".join(out)


def generate(addr_map: Path, dts_path: Path) -> List[str]:
    """Validate spec and write deterministic dts. Returns validation errors."""
    spec = _load(addr_map)
    errs = _validate(spec)
    if errs:
        return errs
    text = render(spec)
    dts_path.parent.mkdir(parents=True, exist_ok=True)
    # newline='\n' so Windows runners don't emit CRLF
    with dts_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return []


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--addr-map", required=True, help="address_map.yaml input")
    p.add_argument("--output", required=True, help="uio_config.dts output")
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if regenerated output diverges from existing file")
    args = p.parse_args(argv)

    out = Path(args.output)
    if args.check:
        if not out.exists():
            print(f"[check] {out} does not exist", file=sys.stderr)
            return 2
        existing = out.read_bytes()
        # Render into memory; do not write
        spec = _load(Path(args.addr_map))
        errs = _validate(spec)
        if errs:
            for e in errs:
                print(f"validation error: {e}", file=sys.stderr)
            return 1
        fresh = render(spec).encode("utf-8")
        if existing != fresh:
            print(f"[check] {out} is stale — regenerate with --output (no --check)",
                  file=sys.stderr)
            return 1
        print(f"[check] OK  {out} sha256={sha256_of(out)}")
        return 0

    errs = generate(Path(args.addr_map), out)
    if errs:
        for e in errs:
            print(f"validation error: {e}", file=sys.stderr)
        return 1
    print(f"[gen] {args.addr_map} -> {args.output}  sha256={sha256_of(out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
