"""Contract 4: address_map.yaml -> uio_config.dts (deterministic).

C2 owns this generator. Output is a UIO-only device-tree overlay that exposes
each peripheral declared in ``hw/vivado/out/address_map.yaml`` to user space
through the in-kernel ``generic-uio`` driver. Vendor-driver bindings (axi-dma,
axi-vdma, digilent-axi-hdmi, xlnx,spike-accel) live in C1's
``sw/petalinux/.../files/spike-accel.dtsi`` and are intentionally NOT emitted
here — the two files coexist by using distinct node names:

    C1 (vendor)      C2 (this file)
    --------------   ------------------
    spike-accel@..   spike_accel-uio@..
    dma@..           axi_dma_feat-uio@..
    vdma@..          vdma_disp-uio@..
    hdmi-tx@..       hdmi_tx-uio@..

Labels are kept as the bare peripheral name from the YAML so downstream
overlays (and ``tests/test_address_map.py``) can still grep for
``spike_accel:``.

CI invariants enforced by ``tests/test_address_map.py``:
  * regenerating the .dts is byte-identical (no clock skew, no dict-order)
  * peripherals are emitted in ascending base address
  * address ranges do not overlap
  * IRQ numbers ∈ [61, 95]   (Zynq-7000 PL → GIC SPI band)

CLI surface:
  ``--addr-map`` / ``--output`` :  generate
  ``--check``                    :  fail if existing file diverges from re-render
  ``--validate``                 :  alias for --check (round-trip self-test;
                                    no write)
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Dict, List


import yaml


# PL IRQ numbers map to SPI #N where N = irq_number - 32. Zynq-7000 PL IRQs
# are routed to GIC SPI 61..95 by the PS irqf2p block.
PL_IRQ_OFFSET = 32

# Header pinned so byte-for-byte diffs against committed file work even when
# tooling versions drift.
_HEADER = """\
/*
 * Auto-generated by tools/ci/gen_dts.py from address_map.yaml.
 * DO NOT EDIT BY HAND. Regenerate after every Vivado BD change.
 * Contract 4 in docs/CONTRACTS.md.
 *
 * Owner: C2 (Driver & SDK).  This file is the *UIO overlay* — it exposes
 * each PL peripheral to user space via generic-uio so libspike_accel can
 * mmap /dev/uioN.  Vendor-driver bindings (axi-dma, axi-vdma, digilent-
 * axi-hdmi, xlnx,spike-accel) are owned by C1 and live in
 *   sw/petalinux/.../recipes-bsp/device-tree/files/spike-accel.dtsi
 * Node names here use the "<name>-uio@<addr>" suffix to avoid collision
 * with the C1 nodes (which keep the historical "<name>@<addr>" form).
 */
"""


def _load(path: Path) -> Dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _validate(spec: Dict) -> List[str]:
    """Return a list of error strings (empty == OK).

    Contract-4 acceptance criteria:
      * required keys present (base, size)
      * IRQ (when present) is an int in PL range [61, 95]
      * no address-range overlap between any two peripherals
      * no IRQ collisions
    """
    errs: List[str] = []
    peri = spec.get("peripherals", {})
    if not peri:
        errs.append("no peripherals declared")
        return errs

    # 1. Required keys
    for name, p in peri.items():
        for k in ("base", "size"):
            if k not in p:
                errs.append(f"{name}: missing '{k}'")
        if "irq" in p and not isinstance(p["irq"], int):
            errs.append(f"{name}: irq must be int")
        if "irq" in p and isinstance(p["irq"], int):
            if not (61 <= p["irq"] <= 95):
                errs.append(f"{name}: irq {p['irq']} outside PL range [61, 95]")

    # 2. No address overlap
    ranges: List = []
    for name, p in peri.items():
        if "base" in p and "size" in p:
            base = int(p["base"])
            end = base + int(p["size"]) - 1
            ranges.append((base, end, name))
    ranges.sort()
    for i in range(1, len(ranges)):
        prev_b, prev_e, prev_n = ranges[i - 1]
        b, e, n = ranges[i]
        if b <= prev_e:
            errs.append(
                f"address overlap: {prev_n} [{prev_b:#x}..{prev_e:#x}] vs "
                f"{n} [{b:#x}..{e:#x}]"
            )

    # 3. No IRQ collision
    seen_irq: Dict[int, str] = {}
    for name, p in peri.items():
        if "irq" in p and isinstance(p["irq"], int):
            irq = p["irq"]
            if irq in seen_irq:
                errs.append(f"irq {irq} used by both {seen_irq[irq]} and {name}")
            seen_irq[irq] = name
    return errs


def render(spec: Dict) -> str:
    """Render address_map dict -> .dts text (deterministic).

    Peripherals are emitted in ascending base address order so the output
    is independent of YAML dict ordering. All nodes are forced to
    ``compatible = "generic-uio"`` since this overlay is consumed by the
    kernel UIO subsystem (vendor compat strings, if present in YAML, are
    informational and consumed by C1's dtsi instead).
    """
    out: List[str] = [
        _HEADER,
        "&amba_pl {",
        '\tcompatible = "simple-bus";'
        ' #address-cells = <1>;'
        ' #size-cells = <1>;',
        "",
    ]
    peri = spec.get("peripherals", {})
    sorted_items = sorted(peri.items(), key=lambda kv: int(kv[1]["base"]))

    for name, p in sorted_items:
        base = int(p["base"])
        size = int(p["size"])
        # NOTE: label = bare peripheral name (back-compat for test_address_map.py
        # which greps for "<name>:"). Node name carries the "-uio" suffix to
        # avoid colliding with C1's spike-accel.dtsi node names.
        node_name = f"{name}-uio@{base:08x}"
        out.append(f"\t{name}: {node_name} {{")
        out.append('\t\tcompatible = "generic-uio";')
        out.append(f"\t\treg = <{base:#x} {size:#x}>;")
        if "irq" in p:
            spi = p["irq"] - PL_IRQ_OFFSET
            out.append(f"\t\tinterrupts = <0 {spi} 4>;")
            out.append("\t\tinterrupt-parent = <&intc>;")
        if p.get("clocks"):
            clk_list = ", ".join(f'"{c}"' for c in p["clocks"])
            out.append(f"\t\tclock-names = {clk_list};")
        out.append('\t\tstatus = "okay";')
        out.append("\t};")
        out.append("")

    out.append("};")
    out.append("")    # trailing newline
    return "\n".join(out)


def generate(addr_map: Path, dts_path: Path) -> List[str]:
    """Validate spec and write deterministic dts. Returns validation errors."""
    spec = _load(addr_map)
    errs = _validate(spec)
    if errs:
        return errs
    text = render(spec)
    dts_path.parent.mkdir(parents=True, exist_ok=True)
    # newline='\n' so Windows runners don't emit CRLF
    with dts_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return []


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main(argv: List[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Generate sw/driver/uio_config.dts from address_map.yaml "
                    "(Contract 4)."
    )
    p.add_argument("--addr-map", required=True, help="address_map.yaml input")
    p.add_argument("--output", required=True, help="uio_config.dts output")
    p.add_argument("--check", action="store_true",
                   help="exit non-zero if regenerated output diverges from "
                        "existing file (does not write)")
    p.add_argument("--validate", action="store_true",
                   help="alias for --check; performs render round-trip "
                        "self-check against the committed file")
    args = p.parse_args(argv)

    out = Path(args.output)
    check_mode = args.check or args.validate
    if check_mode:
        if not out.exists():
            print(f"[check] {out} does not exist", file=sys.stderr)
            return 2
        existing = out.read_bytes()
        # Render into memory; do not write
        spec = _load(Path(args.addr_map))
        errs = _validate(spec)
        if errs:
            for e in errs:
                print(f"validation error: {e}", file=sys.stderr)
            return 1
        fresh = render(spec).encode("utf-8")
        if existing != fresh:
            print(f"[check] {out} is stale - regenerate with --output (no --check)",
                  file=sys.stderr)
            return 1
        print(f"[check] OK  {out} sha256={sha256_of(out)}")
        return 0

    errs = generate(Path(args.addr_map), out)
    if errs:
        for e in errs:
            print(f"validation error: {e}", file=sys.stderr)
        return 1
    print(f"[gen] {args.addr_map} -> {args.output}  sha256={sha256_of(out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
