# runs/remote_machine/run_step6_bt_patched.tcl
#
# Workaround for Main's Layer 1 fix in build_bitstream.tcl (commit 5c7c782):
# the patch used `update_ip_catalog -delete_ipdef <vlnv>` which is NOT a valid
# option in Vivado 2024.1. Per `update_ip_catalog -help`, valid options are
# `-disable_ip` / `-delete_ip` / `-enable_ip`, and they require `-repo_path`.
#
# This wrapper duplicates build_bitstream.tcl with the corrected disable call,
# avoiding touching hw/vivado/build_bitstream.tcl (Main's territory).

set PROJECT spike_zybo
set HW_VIVADO_DIR "C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/hw/vivado"
set OUT_DIR  "$HW_VIVADO_DIR/out"
set REPORTS  "$HW_VIVADO_DIR/reports"
set XLNX_IP  "E:/Applaction/Xilinx/Vivado/2024.1/data/ip"
file mkdir $REPORTS

open_project [file join $OUT_DIR ${PROJECT}.xpr]

# Disable broken roe_framer IP catalog entry (auto_utils.tcl missing in this install).
set _roe_defs [get_ipdefs -quiet -filter {NAME =~ *roe_framer*}]
if {[llength $_roe_defs] > 0} {
    puts "INFO: Disabling partial roe_framer IPs to avoid auto_utils.tcl missing error"
    foreach _idef $_roe_defs {
        if {[catch {update_ip_catalog -disable_ip $_idef -repo_path $XLNX_IP} _err]} {
            puts "WARN: could not disable $_idef: $_err"
        } else {
            puts "INFO: disabled $_idef"
        }
    }
}
unset -nocomplain _roe_defs _idef _err

# Workaround: IPCACHE multi-thread check appears to crash silently in this
# Vivado 2024.1 install. Disable IP cache + single-thread launch.
catch { set_param ip.useCacheStrategy 0 }
catch { set_param ip.checkLicense 0 }
catch { set_param ip.useIpCache 0 }
catch { set_param project.disableIPCache 1 }

# Reset prior runs so a re-invocation (post source-update) starts clean.
# Sub-IP synth runs (system_*_synth_1) must be reset individually — reset_run
# synth_1 does NOT cascade down. Without this, stale sub-IP output (e.g.
# spike_accel from a prior csynth) persists and the new HLS pragmas have no
# visible effect.
catch { reset_run impl_1 }
catch { reset_run synth_1 }
foreach _sub [get_runs -filter {NAME =~ system_*_synth_1}] {
    catch { reset_run $_sub }
}
unset -nocomplain _sub

# CRITICAL: refresh IP catalog & upgrade locked IPs. Without this, dropping
# new HLS-generated component.xml into ip_repo does NOT propagate to the BD
# instance — Vivado shows `WARNING [Project 1-576] IP ... is locked, no OOC
# run will be launched` and silently re-uses the previously-synthesized
# RTL. Symptom: v1=v2=v3 csynth all produce IDENTICAL post-synth utilization
# despite different HLS pragmas.
set _ip_repo "C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/hw/vivado/ip_repo"
set _cur_repos [get_property ip_repo_paths [current_project]]
if {[lsearch $_cur_repos $_ip_repo] < 0} {
    set_property ip_repo_paths [concat $_cur_repos $_ip_repo] [current_project]
}
update_ip_catalog -rebuild
foreach _ip [get_ips -filter {IS_LOCKED == 1}] {
    puts "INFO: upgrading locked IP $_ip"
    catch { upgrade_ip $_ip }
}
unset -nocomplain _ip _ip_repo _cur_repos

# ===== Synth =====
launch_runs synth_1 -jobs 1
wait_on_run synth_1

# ===== Impl =====
launch_runs impl_1 -to_step write_bitstream -jobs 1
wait_on_run impl_1

# ===== Reports =====
open_run impl_1
report_timing_summary -file [file join $REPORTS timing_summary.rpt]
report_utilization     -file [file join $REPORTS utilization.rpt]
catch { report_power   -file [file join $REPORTS power.rpt] }

# ===== Export bitstream + hardware platform =====
set IMPL_DIR [file join $OUT_DIR ${PROJECT}.runs impl_1]
catch {file copy -force [file join $IMPL_DIR system_wrapper.bit] [file join $OUT_DIR system.bit]}
catch {file copy -force [file join $IMPL_DIR system_wrapper.ltx] [file join $OUT_DIR system.ltx]}
write_hw_platform -fixed -force -file [file join $OUT_DIR system.xsa]

# ===== address_map.yaml (Contract 4) =====
set yaml_path [file join $OUT_DIR address_map.yaml]
set fp [open $yaml_path w]
puts $fp "# Auto-generated by run_step6_bt_patched.tcl after Vivado implementation."
puts $fp "soc: zynq-7020"
puts $fp "board: zybo-z7-20"
puts $fp "vivado_version: \"2024.1\""
puts $fp "bitstream: out/system.bit"
puts $fp "hwh: out/system.hwh"
puts $fp "peripherals:"
foreach seg [get_bd_addr_segs -of [get_bd_addr_spaces /ps_0/Data]] {
    set name [get_property NAME $seg]
    set base [get_property OFFSET $seg]
    set size [get_property RANGE $seg]
    puts $fp "  ${name}:"
    puts $fp "    base: ${base}"
    puts $fp "    size: ${size}"
}
puts $fp "memory:"
puts $fp "  ddr3:"
puts $fp "    total_mb: 1024"
puts $fp "    reserved_for_cma: 256"
close $fp

puts "============================================================"
puts "STEP6 PATCHED WRAPPER DONE — reports + bitstream produced."
puts "============================================================"
