# w9_smoke_oneshot.tcl — source xsdb_setup.tcl, override ELF path
# (it lives under vitis_workspace/), run smoke, exit.
source C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/sw/baremetal/spike_accel_w9_smoke/xsdb_setup.tcl
# xsdb_setup.tcl unconditionally sets ::W9_ELF on line 37; override AFTER source.
set ::W9_ELF [file normalize "C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/vitis_workspace/spike_accel_w9_smoke/Debug/spike_accel_w9_smoke.elf"]
# ps7_init.tcl is auto-generated by Vitis under the platform export dir.
# Without it the DDR controller stays in reset → all mwr to 0x10000000 fail.
set ::W9_PS7_INIT [file normalize "C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/vitis_workspace/spike_zybo_baremetal_plat/export/spike_zybo_baremetal_plat/hw/ps7_init.tcl"]
# Source ps7_init.tcl at GLOBAL scope so PCW_SILICON_VER_* constants become
# global. (xsdb_setup.tcl will source it again inside w9_smoke_run; the inner
# source is a no-op for the procs but its `set` of file-scope vars would
# otherwise be local to that proc, which is why the original call fails with
# "PCW_SILICON_VER_1_0: no such variable".)
source $::W9_PS7_INIT
w9_smoke_run
# Let the smoke run; main.c prints fnv1a32 within ~1-3s. Wait 30s to be safe.
after 30000
# Halt CPU before reading memory (mrd requires stopped context in 2024.1)
stop
w9_dump_output C:/Users/jielu/Desktop/Workspace/SpikeYOLO_FPGA/runs/remote_machine/w9_pbt_feat_out.bin
exit 0
